name: ğŸ§¹ Remove lorenzkahl.de branding
on: workflow_dispatch

jobs:
  rebrand:
    runs-on: ubuntu-latest
    if: github.repository != 'lorenzkahl/lorenzkahl.de'
    steps:
      - name: ğŸ“¥ Checkout the repository
        uses: actions/checkout@v4

      - name: ğŸŸ¢ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: ğŸ·ï¸ Run rebranding script
        run: node .github/scripts/lorenzkahl.de-rebrand.js
        env:
          CI: "true" # This tells the script to run in automated mode

      - name: ğŸš€ Commit changes and delete this workflow
        uses: EndBug/add-and-commit@v9
        with:
          remove: '["./.github/workflows/lorenzkahl.de-rebrand.yml"]'
          message: "Up to zero ğŸª"
          tag: "v0.0.1 --force"
